### ISSUE TITLE
Clicking Quake fragment causes app to crash

### ISSUE THREAD

**Issue by MiguelAlexRamirez** [catalinghita8/android-mvvm-rxjava-dagger2#1]
very helpful pedagogical example, it seems to crash when attempting to click a single quake fragment and be redirected tot he URL specified

**Comment by catalinghita8** [comment]
Hi @MiguelAlexRamirez,

I will have a look into and see what's causing the crash.
Can you please give me more details on what device and Android API level have you encountered this?

Thanks,
Catalin

**Comment by catalinghita8** [comment]
I was unable to reproduce this.

Please post a stacktrace.

**Comment by MiguelAlexRamirez** [comment]
First and foremost thank you so much for the prompt replies in trying to help out, the project has been super helpful with learning android concepts, below is a photo of the stacktrace which occurs when clicking on a singular quake fragment -> URL

Various posts state that the nature of the error resides in the fact that the intent needs certain flags declared but when I attempted to do that with the CustomTabIntent without any luck. I have attempted it using an emulator Nexus 5X API 29 and a note 9 running API 28

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by MiguelAlexRamirez** [comment]
I just realized the attachment was sent via proton mail and doesn't seem to be appearing here, my apologies 
![stack_trace](https://user-images.githubusercontent.com/38508680/76107544-80e23000-5f9e-11ea-991d-89ba97d95238.png)

**Comment by catalinghita8** [comment]
@MiguelAlexRamirez I was able to reproduce the issue now. Thanks.
Please check the fixes in `77d21914bc42fb07693f45ea16cd3847a1a205b5` .

 Also get the latest version on `master` branch and it should no longer crash on API 29+.
